#spring.application.name=mobile
spring:
  application:
    name: mobile
  datasource:
    url: jdbc:mysql://localhost:3306/mobile
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080
