#spring.application.name=mobile
spring:
  application:
    name: mobile
  datasource:
    url: jdbc:mysql://localhost:3306/mobile
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
jwt:
  signerKey: "czhaf19GH0VBFMn/QaPPd5lTK8dhNo979NcIZgGfRzgkpm+/PfZI2N0kXUY/lW0o"

server:
  port: 8080
